### ISSUE TITLE
Danny Donahue: Peer Review

### ISSUE THREAD

**Issue by dannydonahue5** [BuntelanNasi/WebTechProject#3]
Hi Dylan, 

I really liked the color palette and idea for your website. I also liked the images you chose and the slideshow for the title page. 

Below are some of the things I noticed:

Two technical issues
- I noticed that when I clicked on the foods under "recipes" I wasn't led anywhere - I assume this is because you are still working on the content. I liked the intent you had with it, though. 
- Everything else was pretty solid in terms of navigation - the only thing I would change is there were some grammar/spelling errors in the "About Me" paragraph. 

Two suggestions
I suggest that you make the images of the food the same size. 
My second suggestion is that you add another page of content, maybe you can separate the recipes out by meal (ex. breakfast, lunch, dinner) or talk about the places/history of the meals. 

This is great for a first draft and I am excited to see the end product and see some of the recipes!

**Comment by BuntelanNasi** [comment]
Hello Danny, 

Thank you for the comments, and I agree with all these points. The foods back then did not work because some codes were incomplete. I fixed some grammar/spelling mistakes in the about me paragraph using Grammarly (it is kind of hard since In not a native English speaker). I made the food images the same size, but I didn't do the second suggestion since most of these foods don't go in the breakfast section. 

Thank you for the feedback!
